name       : libdbusmenu-qt
version    : 0.9.3
release    : 2
source     :
    - http://launchpad.net/ubuntu/+archive/primary/+files/libdbusmenu-qt_0.9.3+16.04.20160218.orig.tar.gz : a8e6358a31c44ccdf1bfc46c95a77a6bfc7fc1f536aadb913ed4f4405c570cf6
license    : LGPL-2.0-later
component  : programming.library
summary    : Provides a Qt implementation of the DBusMenu protocol
description: |
    libdbusmenu-qt library provides a Qt implementation of the DBusMenu protocol. The DBusMenu protocol makes it possible for applications to export and import their menus over DBus.
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %cmake -DWITH_DOC=OFF .
build      : |
    %make
install    : |
    %make_install
